from pathlib import Path


def replace_exact(text, old, new, expected, label):
    count = text.count(old)
    if count != expected:
        raise SystemExit(f'{label}: expected {expected}, found {count}')
    return text.replace(old, new)

app_path = Path('app.js')
app = app_path.read_text(encoding='utf-8')

repls = [
    ('<div class="segmented"><button class="active">Performance</button><button>Efficiency</button><button>Keywords</button></div>', '<div class="segmented"><button class="active" disabled aria-current="true" title="Performance is the only available cross-store preview">Performance</button><button disabled title="Efficiency view is not implemented in the current test runtime">Efficiency · Preview</button><button disabled title="Keyword cross-store view is not implemented in the current test runtime">Keywords · Preview</button></div>', 1, 'cross-store segmented controls'),
    ('<button class="btn secondary">Filter Library</button>', '<button class="btn secondary" disabled aria-disabled="true" title="Global Filter Library is not implemented in the current test runtime">Filter Library · Preview</button>', 1, 'global keyword filter library'),
    ('<button class="btn secondary">Refresh Status</button>', '<button class="btn secondary" disabled aria-disabled="true" title="Live Amazon synchronization is not enabled in this runtime">Refresh Status · Preview</button>', 1, 'sync refresh'),
    ('<button class="btn primary" id="add-store-btn">＋ Add Store</button>', '<button class="btn primary" id="add-store-btn">＋ Add Store · Preview</button>', 1, 'add store preview label'),
    ('<button class="btn secondary">Reconnect</button><button class="btn ghost">Pause Sync</button><button class="btn ghost">Details</button>', '<button class="btn secondary" disabled aria-disabled="true" title="Amazon OAuth backend is not enabled">Reconnect</button><button class="btn ghost" disabled aria-disabled="true" title="Live Amazon synchronization is not enabled">Pause Sync</button><button class="btn ghost" disabled aria-disabled="true" title="Connection detail actions are not implemented in the current test runtime">Details · Preview</button>', 1, 'connected connection controls'),
    ('<button class="btn primary connect-amazon" data-connect-store="${s.id}">Connect Amazon</button><button class="btn ghost">Connection Guide</button>', '<button class="btn primary connect-amazon" data-connect-store="${s.id}">Preview Amazon Connect</button><button class="btn ghost" disabled aria-disabled="true" title="Connection guide is not implemented in the current test runtime">Connection Guide · Preview</button>', 1, 'disconnected connection controls'),
    ('<button class="btn primary">＋ Invite User</button>', '<button class="btn primary" disabled aria-disabled="true" title="User invitation requires authenticated multi-user backend support">＋ Invite User · Preview</button>', 1, 'invite user'),
    ('<button class="btn ghost sm">Daily ⌄</button>', '<button class="btn ghost sm" disabled aria-disabled="true" title="Daily is the only aggregation available in the current imported-data runtime">Daily</button>', 1, 'dashboard granularity'),
    ('<button class="active">${state.pageNo}</button>', '<button class="active" disabled aria-current="page">${state.pageNo}</button>', 2, 'pager current page'),
    ('<button class="btn ghost sm">Sample Filters</button>', '<button class="btn ghost sm" disabled aria-disabled="true" title="Sample Filters are not implemented in the current test runtime">Sample Filters · Preview</button>', 1, 'sample filters'),
    ('<div class="drawer-tabs"><button class="drawer-tab active">Performance</button><button class="drawer-tab">Placements</button><button class="drawer-tab">History</button></div>', '<div class="drawer-tabs"><button class="drawer-tab active" disabled aria-current="true">Performance</button><button class="drawer-tab" disabled aria-disabled="true" title="Placement history is not available from imported search-term data">Placements · Preview</button><button class="drawer-tab" disabled aria-disabled="true" title="Search-term history view is not implemented yet">History · Preview</button></div>', 1, 'search term drawer tabs'),
    ("$('#add-store-btn')?.addEventListener('click',()=>openModal('Create Store Workspace',`<label class=\"field\"><span>KeywordOS Store Name</span><input class=\"input\" placeholder=\"e.g. Brand-US-04\"></label><label class=\"field top-gap\"><span>Marketplace</span><select class=\"select\"><option>Amazon.com</option><option>Amazon.ca</option><option>Amazon.co.uk</option></select></label><div class=\"notice-banner top-gap\">Creating a workspace does not connect or link an Amazon account. OAuth is a separate step.</div>`,[{label:'Cancel',action:closeModal},{label:'Create Workspace',type:'primary',action:()=>{closeModal();toast('Store workspace preview created.','success')}}]));", "$('#add-store-btn')?.addEventListener('click',()=>openModal('Create Store Workspace · Preview',`<label class=\"field\"><span>KeywordOS Store Name</span><input class=\"input\" placeholder=\"e.g. Brand-US-04\"></label><label class=\"field top-gap\"><span>Marketplace</span><select class=\"select\"><option>Amazon.com</option><option>Amazon.ca</option><option>Amazon.co.uk</option></select></label><div class=\"notice-banner top-gap\"><b>Preview only.</b> No Store workspace is created or persisted in the current public test runtime.</div>`,[{label:'Close Preview',action:closeModal}]));", 1, 'add store modal'),
    ("function openAmazonConnectPreview(storeId){const st=STORES.find(x=>x.id===storeId);openModal(`Connect ${st.name} to Amazon Ads`,`<span class=\"modal-kicker\">INDEPENDENT OAUTH</span><div class=\"oauth-steps top-gap\"><div class=\"done\"><b>1</b><span>Create Store Workspace</span></div><i>→</i><div class=\"active\"><b>2</b><span>Amazon OAuth</span></div><i>→</i><div><b>3</b><span>Select Advertiser</span></div><i>→</i><div><b>4</b><span>Bind Profile</span></div></div><div class=\"execution-boundary top-gap\"><span>STORE</span><b>${st.code}</b><i>→</i><span>CONNECTION</span><b>${st.connection}</b><i>→</i><span>ADVERTISER</span><b>Selected after OAuth</b></div><div class=\"notice-banner top-gap\">Frontend preview only. No Amazon credential is requested or stored in this build.</div>`,[{label:'Cancel',action:closeModal},{label:'Continue with Amazon',type:'primary',action:()=>{closeModal();toast('OAuth backend will be connected in the API phase.','success')}}]);}", "function openAmazonConnectPreview(storeId){const st=STORES.find(x=>x.id===storeId);openModal(`Amazon Ads Connection Preview · ${st.name}`,`<span class=\"modal-kicker\">INDEPENDENT OAUTH · PREVIEW</span><div class=\"oauth-steps top-gap\"><div class=\"done\"><b>1</b><span>Create Store Workspace</span></div><i>→</i><div class=\"active\"><b>2</b><span>Amazon OAuth</span></div><i>→</i><div><b>3</b><span>Select Advertiser</span></div><i>→</i><div><b>4</b><span>Bind Profile</span></div></div><div class=\"execution-boundary top-gap\"><span>STORE</span><b>${st.code}</b><i>→</i><span>CONNECTION</span><b>${st.connection}</b><i>→</i><span>ADVERTISER</span><b>Selected after OAuth</b></div><div class=\"notice-banner top-gap\"><b>Preview only.</b> No Amazon credential is requested or stored, and no OAuth flow is started in this runtime.</div>`,[{label:'Close Preview',action:closeModal}]);}", 1, 'Amazon connection preview'),
]

for old, new, expected, label in repls:
    app = replace_exact(app, old, new, expected, label)

app_path.write_text(app, encoding='utf-8')

ui_path = Path('ui-actions.js')
ui = ui_path.read_text(encoding='utf-8')
ui = replace_exact(ui, "if (input.id === 'log-search' || input.id === 'kw-search') return true;", "if (input.id === 'log-search' || input.id === 'kw-search' || input.id === 'global-keyword-search') return true;", 1, 'global keyword search handler')

anchor = "  function markKnownInactiveControls() {\n"
insert = """  function markStaticShellTruth() {\n    disableButton($('.sidebar-collapse'), 'Sidebar collapse is not implemented in the current test runtime.');\n    disableButton($('#tool-switcher'), 'Advertising is the only active tool workspace in the current test runtime.');\n    disableButton($('.product-menu'), 'Product suite switching is not implemented in the current test runtime.');\n    $$('.suite-nav button').forEach((button) => disableButton(button, 'Suite navigation is preview-only in this runtime.'));\n    $$('.header-action').forEach((button) => disableButton(button, 'This global header action is not implemented in the current test runtime.'));\n    $$('.side-link:not([data-page])').forEach((button) => disableButton(button, 'Help Center integration is not implemented in the current test runtime.'));\n  }\n\n"""
ui = replace_exact(ui, anchor, insert + anchor, 1, 'static shell truth')
ui = replace_exact(ui, "  function start() {\n    markKnownInactiveControls();", "  function start() {\n    markStaticShellTruth();\n    markKnownInactiveControls();", 1, 'static shell startup')
ui_path.write_text(ui, encoding='utf-8')
